# Generated by Django 4.0 on 2021-12-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_photo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
